[book]
authors = ["Henk Oordt", "Marc Schoolderman", "Folkert de Vries", "Ruben Nijveld"]
title = "Teach-rs - Exercises"
language = "en"
multilingual = false
src = "."

[build]
build-dir = "./target"
